### ISSUE TITLE
Container is missing Intl & Soap extensions

### ISSUE THREAD

**Issue by DannyvdSluijs** [phpstan/docker-image#3]
I've tried to run the phpstan project over some of my personal and professional codebase as I very much like the issues it can detect. However quite some of my repositories use the Intl extension. Ans the container crashes with issues like:

Fatal error: Class 'IntlDateFormatter' not found in /composer/vendor/phpstan/phpstan/src/Reflection/Php/PhpParameterReflection.php on line 41

Could the container get support for these type of extensions ? I believe Soap to be another extension to be very basic as another codebase is giving me the following errors:
  243    Instantiated class SoapClient not found.                         
  245    Call to method __getTypes() on an unknown class SoapClient.      
  255    Call to method __getFunctions() on an unknown class SoapClient.

**Comment by tommy-muehle** [comment]
Hi @DannyvdSluijs,

our Docker images (latest and 0.6) are based on/extend the [official PHP ones](https://hub.docker.com/_/php/).  
Exactly on the [PHP 7.1 alpine image](https://github.com/docker-library/php/blob/ec02e1bcf1196ed3f8b74ecc956cf81554e32db8/7.1/alpine/Dockerfile) to match prerequisities and get the most performance.

So only these configured extensions are available. Also because PHPStan needs no further extensions to run itself.

But to solve your problem. You can simply extend our image and add your custom requirements. 
For example you can use this Dockerfile:

```
FROM phpstan/phpstan:latest
RUN apk add --no-cache --virtual .persistent-deps icu-dev libxml2-dev \
    && docker-php-ext-configure intl --enable-intl \
    && docker-php-ext-configure soap --enable-soap \
    && docker-php-ext-install intl \
    && docker-php-ext-install soap
```

Hope that helps you!
